apiVersion: v1
kind: Secret
metadata:
  name: barbershop-secret
  namespace: barbershop
type: Opaque
stringData:
  POSTGRES_DB: barbershop
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  APP_AUTH_EMAIL: admin@barbershop.com
  APP_AUTH_PASSWORD: admin123
  APP_AUTH_DISPLAY_NAME: Administrador
  GRAFANA_ADMIN_USER: admin
  GRAFANA_ADMIN_PASSWORD: change-me-in-production
